---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenbot
  labels:
    app: tenbot
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: tenbot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tenbot
    spec:
      containers:
      - name: tenbot
        image: tenbot:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: tenbot-env
      terminationGracePeriodSeconds: 180